### ISSUE TITLE
Fix package.json to work on Windows

### ISSUE THREAD

**Issue by matthillco** [andybelldesign/hylia#30]
Under Git Bash terminal on Windows, the `npm start` task fails due to Windows not understanding the tasks described in `package.json`. This is due to two reasons:

* Windows environment variables are declared differently than *nix OSs
* Windows does not understand single apostrophes when used in task parameters in `package.json`.

This can be fixed by doing the following:

* Use the `core-env` module to handle correct setup of environment variables across multiple platforms: (https://www.npmjs.com/package/cross-env)
* Replace single quotes with escaped double quotes, so `'` becomes `\"`

I've tested this on my own installation **Windows 7, Git for Windows 2.12.2, Node 10.16.0, Npm 6.9.0** and it seems fine, but would need to be tested by others before merging (in particular, for users with Windows 10).

I'm happy to raise a PR, but I don't have write permissions.

**Comment by mandaputtra** [comment]
Do you know how to get up in running locally with windows?  What should I add or do? I do have `win-node-env` installed globally. But that only for NODE_ENV.

```
[0] 'np' is not recognized as an internal or external command,
[0] operable program or batch file.
[2] The filename, directory name, or volume label syntax is incorrect.
[3] '--watch'' is not recognized as an internal or external command,
[3] operable program or batch file.
[4] 'np' is not recognized as an internal or external command,
[4] operable program or batch file.
[6] 'serve'' is not recognized as an internal or external command,
[6] operable program or batch file.
[3] --watch' exited with code 1
[2] sass:process exited with code 1
[0] np exited with code 1
[6] serve' exited with code 1
[4] np exited with code 1
[1] run exited with code 1
[5] run exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hylia@0.1.0 start: `concurrently 'npm run sass:process -- --watch' 'npm run serve'`
npm ERR! Exit status 1
```

**Comment by matthillco** [comment]
Hi @mandaputtra. You should be able to get this working using the changes I suggested above. In your Hylia root folder, run `npm install --save-dev cross-env`, then edit the `serve` task in `package.josn` as described above:

```"serve": "cross-env ELEVENTY_ENV=development npx eleventy --serve",```

Also, edit the `start` task in `package.json` and replace the single quotes with double quotes and escape them, like this:

```"start": "concurrently \"npm run sass:process -- --watch\" \"npm run serve\"",```

**Comment by andybelldesign** [comment]
Cheers for this @matthillco. As we discussed away from this issue, I'll assign you to this. If you can't get around to it, just let us know and I'll let someone else claim it 🙂
