### ISSUE TITLE
Overflow "bug" on mobile

### ISSUE THREAD

**Issue by seansmyth** [andybelldesign/hylia#36]
Hey, just spotted a little overflow issue on Firefox on Android - haven't tested on other browsers.

Just occurs on this link in particular
https://hylia.website/posts/a-post-with-code-samples/

![Screenshot_20190620_200253_org mozilla firefox](https://user-images.githubusercontent.com/7364220/59934421-646b8b00-9443-11e9-903d-3f72ae018b25.jpg)
![Screenshot_20190620_200301_org mozilla firefox](https://user-images.githubusercontent.com/7364220/59934422-646b8b00-9443-11e9-8071-37d1395bd7cb.jpg)

Hope that's ok? Don't know if you need more info? :)

Thaaaaaanks!

**Comment by andybelldesign** [comment]
Thanks @seansmyth, this is really helpful. 

Can you just get a report, on your device, from https://mybrowser.fyi please?

**Comment by marcusrelacion** [comment]
Hey @andybelldesign! I did a little bit of digging and found some starting points:

- Once the viewport is < 943px wide the full-bleed utility causes the horizontal scrollbar to appear.
- As the viewport gets smaller, the code examples in the textblock are not breaking to new lines which is causing it to run off the page:
<img width="375" alt="Screenshot 2019-06-21 17 01 49" src="https://user-images.githubusercontent.com/6185899/59951262-5b2fed80-9446-11e9-9e23-e181138e1623.png">
- In addition to the code example not wrapping, the h2 in the post body is also running off the page:
<img width="341" alt="Screenshot 2019-06-21 17 03 03" src="https://user-images.githubusercontent.com/6185899/59951359-b95cd080-9446-11e9-86d4-cfe033750b89.png">

I'd be happy to open a pull request to help get this fixed up!

**Comment by andybelldesign** [comment]
Awesome, I'd really appreciate it if you did @marcusrelacion :)

**Comment by andybelldesign** [comment]
Fixed with #41
