### ISSUE TITLE
External link boolean is required on globals in CMS

### ISSUE THREAD

**Issue by jonnyburch** [andybelldesign/hylia#39]
<img width="639" alt="Screenshot 2019-06-21 17 02 41" src="https://user-images.githubusercontent.com/3037815/59949605-82e57c80-946b-11e9-93d6-99ff352add7c.png">

External link is required, it shouldn't be! `required: false` looks to be the solution

**Comment by andybelldesign** [comment]
Cheers, Jonny. This should be a straight-forward fix.

**Comment by brendansparrow** [comment]
Hi, Andy. Thanks for building this theme, I'm happy to jump on this!
