### ISSUE TITLE
Scheduled posts appear in tag listing

### ISSUE THREAD

**Issue by trovster** [andybelldesign/hylia#52]
When visiting a [tag archive page](https://hylia.website/tags/demo-content/) it shows scheduled posts in the future. I expect these posts not to display.

**Comment by andybelldesign** [comment]
Good catch. Cheers, @trovster!

**Comment by trovster** [comment]
I don't think this is the best solution. The other areas of the site make use of "draft" flag as well as the date. This only uses date. It could also generate an empty page if all the tags' posts are "draft".
