### ISSUE TITLE
Sticky footer by default

### ISSUE THREAD

**Issue by jonnyburch** [andybelldesign/hylia#56]
Might be a nice improvement to stick the footer:

```
body {
  scroll-behavior: smooth;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

main {
  flex: 1;
}
```
(or equivalent)

**Comment by andybelldesign** [comment]
It's a good idea, @jonnyburch. I'll label it as a good first issue. 

If anyone comes along to implement this, this best place to implement it would be in [global.scss](https://github.com/andybelldesign/hylia/blob/master/src/scss/global.scss#L23).
