### ISSUE TITLE
Bitbucket support

### ISSUE THREAD

**Issue by djmtype** [andybelldesign/hylia#66]
Is there something we need to add to make NetlifyCMS work with Hylia on Bitbucket? As of July 26, 2019, NetlifyCMS should be compatible. [Netlify CMS 2.0 launches with Bitbucket support and a new monorepo architecture](https://www.netlifycms.org/blog/2018/07/netlify-cms-2-0-launches-with-bitbucket-support-and-a-new-monorepo-architecture/) Yet, I can't seem to enable the Git Gateway options if the repo is hosted via Bitbucket.

**Comment by andybelldesign** [comment]
Hey Scott! I’m not really sure about this to be honest. I think the Netlify CMS team might have some more knowledge on it.

**Comment by djmtype** [comment]
Thanks @andybelldesign. I'll see if I can find out.
