### ISSUE TITLE
Kindly keep git history linear by avoiding merge commits

### ISSUE THREAD

**Issue by shreeshbhat** [andybelldesign/hylia#71]
I really love this project, Andy.
A small change in this repo's settings would help keep git history linear, clean and easy to navigate.
Please avoid merge commits while merging PRs.

Squash and merge option would be easier I think.

https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits

Reasoning : 
https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/

**Comment by shreeshbhat** [comment]
@andybelldesign : I still see merge commits happening to this repo.
Please try out squash and merge option while merging PRs, that will keep git history clean and easy to read.

**Comment by andybelldesign** [comment]
I’ll keep it how it is, cheers 👍
